server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
      hibernate:
        ddl-auto: create
        show-sql: true

